---
- name: "{{ hadoop_task_prefix }} Create group"
  ansible.builtin.group:
    name: "{{ hadoop_group }}"
    state: present

- name: "{{ hadoop_task_prefix }} Create user"
  ansible.builtin.user:
    name: "{{ hadoop_user }}"
    shell: "{{ hadoop_user_shell }}"
    group: "{{ hadoop_group }}"
    state: present

- name: "{{ hadoop_task_prefix }} Download checksum"
  ansible.builtin.uri:
    url: "{{ hadoop_download_url_file }}.sha512"
    return_content: true
  register: hadoop_download_checksum_raw

- name: "{{ hadoop_task_prefix }} Download tarball"
  ansible.builtin.set_fact:
    hadoop_download_checksum: "{{ hadoop_download_checksum_raw.content.split(' = ')[1] }}"

- name: "{{ hadoop_task_prefix }} Download tarball"
  ansible.builtin.get_url:
    url: "{{ hadoop_download_url_file }}"
    dest: "{{ hadoop_path_tarball }}"
    checksum: "sha512:{{ hadoop_download_checksum }}"

- name: "{{ hadoop_task_prefix }} Unpack tarball"
  ansible.builtin.unarchive:
    src: "{{ hadoop_path_tarball }}"
    dest: "{{ hadoop_path_base }}"
    remote_src: true

...
