---
- name: "{{ hadoop_task_prefix }} Create group"
  ansible.builtin.group:
    name: "{{ hadoop_group }}"
    state: present

- name: "{{ hadoop_task_prefix }} Create user"
  ansible.builtin.user:
    name: "{{ hadoop_user }}"
    shell: "{{ hadoop_user_shell }}"
    group: "{{ hadoop_group }}"
    state: present

- name: "{{ hadoop_task_prefix }} Download checksum"
  ansible.builtin.uri:
    url: "{{ hadoop_download_url_checksum }}"
    return_content: true
  register: hadoop_download_checksum_raw

- name: "{{ hadoop_task_prefix }} Extract checksum"
  ansible.builtin.set_fact:
    hadoop_download_checksum: "{{ hadoop_download_checksum_raw.content.split(' = ')[1] }}"

- name: "{{ hadoop_task_prefix }} Download tarball"
  ansible.builtin.get_url:
    url: "{{ hadoop_download_url_file }}"
    dest: "{{ hadoop_path_tarball }}"
    checksum: "{{ hadoop_download_checksum_algo }}:{{ hadoop_download_checksum }}"

- name: "{{ hadoop_task_prefix }} Unpack tarball"
  ansible.builtin.unarchive:
    src: "{{ hadoop_path_tarball }}"
    dest: "{{ hadoop_path_base }}"
    remote_src: true

- name: "{{ hadoop_task_prefix }} Copy binaries"
  ansible.builtin.copy:
    src: "{{ hadoop_path_unpacked }}"
    dest: "{{ hadoop_path_install }}"
    remote_src: true

- name: "{{ hadoop_task_prefix }} Create data directory"
  file:
    path: "{{ hadoop_path_data }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: '0755'

- name: "{{ hadoop_task_prefix }} Template exclusion list"
  template:
    src: "{{ hadoop_template_exclusion_list }}"
    dest: "{{ hadoop_path_data }}/exclusion-list"
    owner: root
    group: root
    mode: '0644'
  #notify: hadoop_handler_refresh_nodes

- name: "{{ hadoop_task_prefix }} Template core-site.xml"
  template:
    src: "{{ hadoop_template_core_site_xml }}"
    dest: "{{ hadoop_path_config }}/core-site.xml"
    owner: root
    group: root
    mode: '0644'

- name: "{{ hadoop_task_prefix }} Template hdfs-site.xml"
  template:
    src: "{{ hadoop_template_hdfs_site_xml }}"
    dest: "{{ hadoop_path_config }}/hdfs-site.xml"
    owner: root
    group: root
    mode: '0644'

- name: "{{ hadoop_task_prefix }} Template hadoop-env.sh"
  template:
    src: "{{ hadoop_template_hadoop_env_sh }}"
    dest: "{{ hadoop_path_config }}/hadoop-env.sh"
    owner: root
    group: root
    mode: '0644'

- name: "{{ hadoop_task_prefix }} Template yarn-env.sh"
  template:
    src: "{{ hadoop_template_yarn_env_sh }}"
    dest: "{{ hadoop_path_config }}/yarn-env.sh"
    owner: root
    group: root
    mode: '0644'

- name: "{{ hadoop_task_prefix }} Template yarn-site.xml"
  template:
    src: "{{ hadoop_template_yarn_site_xml }}"
    dest: "{{ hadoop_path_config }}/yarn-site.xml"
    owner: root
    group: root
    mode: '0644'

- name: "{{ hadoop_task_prefix }} Template mapred-site.xml"
  template:
    src: "{{ hadoop_template_mapred_site_xml }}"
    dest: "{{ hadoop_path_config }}/mapred-site.xml"
    owner: root
    group: root
    mode: '0644'
...
